# PHP Card Authentication - Docker Compose Configuration
# This file provides a development environment for the card authentication system

version: '3.8'

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: php-card-auth-app
    ports:
      - "${APP_PORT:-8000}:8000"
    volumes:
      - .:/app
      - ./logs:/app/logs
      - /app/vendor  # Anonymous volume for vendor to prevent overwrites
    environment:
      - APP_ENV=${APP_ENV:-development}
      - SECRET_API_KEY=${SECRET_API_KEY}
      - DEVELOPER_ID=${DEVELOPER_ID:-000000}
      - VERSION_NUMBER=${VERSION_NUMBER:-0000}
      - SERVICE_URL=${SERVICE_URL:-https://cert.api2.heartlandportico.com}
      - ENABLE_REQUEST_LOGGING=${ENABLE_REQUEST_LOGGING:-false}
    env_file:
      - .env
    networks:
      - card-auth-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/api/config.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production service (optional)
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: php-card-auth-app-prod
    ports:
      - "${PROD_PORT:-8001}:8000"
    environment:
      - APP_ENV=production
      - SECRET_API_KEY=${SECRET_API_KEY}
      - DEVELOPER_ID=${DEVELOPER_ID:-000000}
      - VERSION_NUMBER=${VERSION_NUMBER:-0000}
      - SERVICE_URL=${SERVICE_URL:-https://cert.api2.heartlandportico.com}
      - ENABLE_REQUEST_LOGGING=false
    env_file:
      - .env
    networks:
      - card-auth-network
    restart: unless-stopped
    profiles:
      - production
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000/api/config.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Testing service
  tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: php-card-auth-tests
    volumes:
      - .:/app
    environment:
      - APP_ENV=testing
      - SECRET_API_KEY=skapi_cert_test_key
      - DEVELOPER_ID=000000
      - VERSION_NUMBER=0000
      - SERVICE_URL=https://cert.api2.heartlandportico.com
    networks:
      - card-auth-network
    profiles:
      - testing
    command: ["./vendor/bin/phpunit", "--colors=always", "--testdox"]

# Custom network for service communication
networks:
  card-auth-network:
    driver: bridge

# Development override example
# Create docker-compose.override.yml for local development customizations