global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'go-payments-api'
    static_configs:
      - targets: ['go-payments-api:8000']
    metrics_path: '/metrics'